CREATE TABLE ENDERECO (
    ID SERIAL PRIMARY KEY,
    CEP CHAR(10) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10),
    PTO_REFERENCIA VARCHAR(255),

    CONSTRAINT formato_cep CHECK(cep ~ '^\d{2}\.\d{3}-\d{3}$'),
    CONSTRAINT formato_estado CHECK(estado ~ '^[A-Z]{2}$'),
    CONSTRAINT formato_numero CHECK(numero ~ '^([1-9]\d{1,9})|(S/N)$')
);

CREATE TABLE VEICULO (
    ID SERIAL PRIMARY KEY,
    PLACA CHAR(8) NOT NULL,
    MARCA VARCHAR(45) NOT NULL,
    MODELO VARCHAR(45) NOT NULL,

    CONSTRAINT unique_placa UNIQUE(placa),
    CONSTRAINT formato_placa CHECK(placa ~ '^[A-Z]{3}-\d{4}$')
);

CREATE TABLE MOTORISTA (
    ID SERIAL PRIMARY KEY,
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CNH VARCHAR(20) NOT NULL,
    RG VARCHAR(45) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    DISPONIVEL BOOLEAN NOT NULL DEFAULT false,
    ENDERECO_ID INT NOT NULL REFERENCES endereco ON DELETE RESTRICT,
    VEICULO_ID INT REFERENCES veiculo ON DELETE SET DEFAULT NULL,

    CONSTRAINT unique_cpf UNIQUE(cpf),
    CONSTRAINT unique_rg UNIQUE(rg),
    CONSTRAINT unique_motorista_endereco_id UNIQUE(endereco_id),

    CONSTRAINT formato_cpf CHECK(cpf ~ '^\d{3}\.\d{3}\.\d{3}-\d{2}$'),
    CONSTRAINT formato_telefone CHECK(telefone ~ '^\(\d{2}\)(\d)?\d{4}-\d{4}$')
);

CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    CNPJ CHAR(18) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    ENDERECO_ID INT NOT NULL REFERENCES endereco ON DELETE RESTRICT,

    CONSTRAINT unique_cnpj UNIQUE(cnpj),
    CONSTRAINT unique_cliente_endereco_id UNIQUE(endereco_id),
    
    CONSTRAINT formato_cnpj CHECK(cnpj ~ '^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$'),
    CONSTRAINT formato_telefone CHECK(telefone ~ '^\(\d{2}\)(\d)?\d{4}-\d{4}$')
);

CREATE TABLE PEDIDO (
    ID SERIAL PRIMARY KEY,
    TIMESTAMP_REQUISICAO TIMESTAMP NOT NULL,
    PRODUTO VARCHAR(255) NOT NULL,
    QTD_VOLUMES INT NOT NULL DEFAULT 0,
    PESO_ENCOMENDA INT NOT NULL DEFAULT 0,
    DISTANCIA INT,
    PRECO_FRETE DECIMAL(10,2),
    OBSERVACOES VARCHAR(255),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'EM_PROCESSAMENTO',
    CLIENTE_ID INT NOT NULL REFERENCES cliente ON DELETE CASCADE,
    ENDERECO_ORIGEM INT NOT NULL REFERENCES endereco ON DELETE RESTRICT,
    ENDERECO_DESTINO INT NOT NULL REFERENCES endereco ON DELETE RESTRICT,

    CONSTRAINT uniques_cliente UNIQUE(timestamp_requisicao, cliente_id),

    CONSTRAINT enum_status
    CHECK (status LIKE 'EM_PROCESSAMENTO'
        OR status LIKE 'EM_SEPARACAO'
        OR status LIKE 'ENVIADO'
        OR status LIKE 'RECEBIDO'
        )
);

CREATE TABLE VIAGEM (
    ID SERIAL PRIMARY KEY,
    QTD_VOLUMES INT NOT NULL,
    PESO_VOLUMES INT NOT NULL,
    TIMESTAMP_INICIO TIMESTAMP NOT NULL,
    TIMESTAMP_FIM TIMESTAMP,
    OBSERVACOES VARCHAR(255),
    MOTORISTA_ID INT REFERENCES motorista ON DELETE RESTRICT,
    PEDIDO_ID INT REFERENCES pedido ON DELETE CASCADE,

    CONSTRAINT uniques_viagem UNIQUE(timestamp_inicio, motorista_id),
    CONSTRAINT datas_inicio_fim CHECK((TIMESTAMP_INICIO < TIMESTAMP_FIM) OR (TIMESTAMP_FIM IS NULL))
);
